# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e2beca77abc634ccef3820aa0efd8b8d532967af10920d78fbe7b3c2ed46c654bf7c16fe33b24cef65341e4e1e73ba863f38772dbdf3ea11862a7bbd843deb5

test:
  secret_key_base: a5203d6ca46db4882c1e434e29969650076791acc1150e745f123bda30f957beddd5728256f90c42dfee0befc7b354f9b3e277ebce88a275390d29830b29fca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
